spring.application.name=pet_link

server.port=${PORT:8080}

# Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-delicate-silence-acmogbmc-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QVRwKbcL5aS2
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Pool de conexões
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000


# Actuator (monitoramento)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Logs
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=WARN

# Configurações de upload (opcional)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Timezone
spring.jackson.time-zone=America/Sao_Paulo

jwt.expiration=900000
jwt.secret= ipK8Gdt_#bpnKMOJ4LZa9Mr&lB506z3-n9BHSudfjy4ad$1u0_K5k3iDVANAX_4uFvs&MD3_MSPKivSDhi37TOZ4om#_VfvSqQkPP57$VX_bex!KtU!zcvkO5#F-3cIYn&-JH$3rbJY8s6ni4pmDn_EOWy!_u#hEmP#=Yib2BSvVyeNv0a0&HQqTLoa1ypw83!ic3rWPpkeZ&U82ScnGG=IhKwN6pt_&NOHqv#CDYGxKmegF2mf!S$garWRcw&#Y&P2o=-OH$eL6=!tWjqDffv&V&5m&p9Iy-PH2TJ9tIsRfCRrgDQMogiMY#0QDpQ!-9QpOdzzm0jZAy#GdBQYCrcgt

logging.pattern.console = %d{yyyy-MM-dd HH:mm} == %logger{40} >>> %msg%n